In [18]:
import torch
x = torch.rand(5, 3)
print(x)

tensor([[0.1180, 0.1217, 0.7356],
        [0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565],
        [0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])


In [19]:
# Zero dimension tensor is scalar
# One dimension tensor is vector or arrays
# Two dimension tensor is matrix e.g is Black and white Image
# Three dimension tensor is tensor e.g is Colored image a.k.a RGB-alpha image where alpha is intensity 

In [20]:
print(torch.__version__)

2.11.0+cpu


In [21]:
if torch.cuda.is_available():
    print("GPU is available!!")
    print(f"GPU is : {torch.cuda.get_device_name(0)}")
else: 
    print("GPU is not available!!")

GPU is not available!!


In [22]:
# empty tensor
t1 = torch.empty(3,3)  # allocated the memory for a tensor
t1

tensor([[-5.2421e+02,  1.3971e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [23]:
type(t1)

torch.Tensor

In [24]:
t0 = torch.zeros(3,3)
t0

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [25]:
t_ones = torch.ones(3,3)
t_ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [26]:
t_rand = torch.rand(3,3)
t_rand # creating 3,3 tensor with random values

tensor([[0.4440, 0.9478, 0.7445],
        [0.4892, 0.2426, 0.7003],
        [0.5277, 0.2472, 0.7909]])

In [27]:
# use of seed to keep random value same
t_rand_unseed= torch.rand(3,3)
t_rand_unseed
torch.manual_seed(100) # creating seed for next 100 lines this seed will create same random value
t_rand_seed1 = torch.rand(3,3)
t_rand_seed1

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539],
        [0.2627, 0.0428, 0.2080]])

In [28]:
# Custom tensors
my_tensor = torch.tensor([[1,2,3],[4,5,6]])
my_tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [29]:
# Tensor creation
print("arrange: ", torch.arange(0,10,2)) # 0 to 10 with steps of 2 
print("Linear space: ", torch.linspace(0,20,10)) # 0 to 20 in 10 division 
print("EYE : ", torch.eye(5)) # 1 in diagonal for 5x5 tensor  
print("Full : ", torch.full((3,3),7)) # 3x3 tensor with 7 in all values  

arrange:  tensor([0, 2, 4, 6, 8])
Linear space:  tensor([ 0.0000,  2.2222,  4.4444,  6.6667,  8.8889, 11.1111, 13.3333, 15.5556,
        17.7778, 20.0000])
EYE :  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
Full :  tensor([[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]])


In [30]:
# my_tensor
my_tensor.shape # two rows and three column 

torch.Size([2, 3])

In [31]:
# creating similar shape tensor as my_tensor with random data
my_tensor1 = torch.empty_like(my_tensor)
my_tensor1 

tensor([[4570841374428044698, 4562866088310343597, 4558661444154925340],
        [4493264751667737696,          1062768230,                   0]])

In [32]:
# creating similar shape tensor as my_tensor with all zero
my_tensor0 = torch.zeros_like(my_tensor)
my_tensor0

tensor([[0, 0, 0],
        [0, 0, 0]])

In [33]:
# creating similar shape tensor as my_tensor with all ones
my_tensor11 = torch.ones_like(my_tensor)
my_tensor11

tensor([[1, 1, 1],
        [1, 1, 1]])

In [34]:
# creating similar shape tensor as my_tensor with all random float value
my_tensor2 = torch.rand_like(my_tensor)
my_tensor2

NotImplementedError: "check_uniform_bounds" not implemented for 'Long'

In [35]:
# Datatypes
my_tensor.dtype

torch.int64

In [36]:
my_f_tensor = torch.rand([3,3]) # created 3x3 random tensor 
my_f_tensor

tensor([[0.1180, 0.1217, 0.7356],
        [0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

In [37]:
my_i_tensor = torch.rand([3,3], dtype=torch.float16) # created 3x3 random tensor  .rand works with float only
my_i_tensor

tensor([[0.1367, 0.8198, 0.6113],
        [0.9272, 0.6543, 0.7783],
        [0.4453, 0.7476, 0.8169]], dtype=torch.float16)

In [38]:
my_i8_tensor = torch.tensor([
    [1.0,2.0],
    [3.0,4.0],
    ], dtype=torch.int8) # created 3x3 random tensor  .rand works with float only
my_i8_tensor

tensor([[1, 2],
        [3, 4]], dtype=torch.int8)

In [39]:
# changing the data type of the tensor
my_newf_tensor = my_tensor.to(torch.float16)
my_newf_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float16)

In [40]:
# now applying the rand_like 
my_newf_tensor1 = torch.rand_like(my_newf_tensor) 
my_newf_tensor1

tensor([[0.5454, 0.0420, 0.1885],
        [0.8257, 0.9277, 0.9395]], dtype=torch.float16)

In [41]:
# now applying the rand_like with dtype
my_new_tensor1 = torch.rand_like(my_tensor , dtype=torch.float16) 
my_new_tensor1

tensor([[0.2026, 0.4380, 0.5688],
        [0.3696, 0.8530, 0.2988]], dtype=torch.float16)

In [42]:
# Scalar Operations
t1 = torch.rand(2,2)
t1

tensor([[0.8902, 0.5163],
        [0.0359, 0.6476]])

In [ ]:
# Addition 
t1 +2 # Inplace modification is not done
# t1 = t1 + 2 # for inplace modification

tensor([[2.8902, 2.5163],
        [2.0359, 2.6476]])

In [44]:
# subtraction
t1-1

tensor([[-0.1098, -0.4837],
        [-0.9641, -0.3524]])

In [ ]:
# Multiplication 
t1*3

tensor([[2.6706, 1.5488],
        [0.1077, 1.9429]])

In [46]:
# int division
t1/2

tensor([[0.4451, 0.2581],
        [0.0179, 0.3238]])

In [47]:
# 
t1//2

tensor([[0., 0.],
        [0., 0.]])

In [ ]:
# Mod
t1%0.5 # Mod gives remainder

tensor([[0.8902, 0.5163],
        [0.0359, 0.6476]])

In [50]:
my_i8_tensor%2

tensor([[1, 0],
        [1, 0]], dtype=torch.int8)

In [51]:
# power
t1**2

tensor([[0.7925, 0.2665],
        [0.0013, 0.4194]])

In [53]:
# Integer division 
t2 = t1*50
t2//3

tensor([[14.,  8.],
        [ 0., 10.]])

In [54]:
# Element wise operation 
# addition
t1+t2

tensor([[45.4001, 26.3298],
        [ 1.8301, 33.0293]])

In [55]:
# Element wise operation 
# subtraction
t1-t2

tensor([[-43.6197, -25.2973],
        [ -1.7583, -31.7340]])

In [56]:
# Element wise operation 
# Multiplication
t1*t2

tensor([[39.6226, 13.3268],
        [ 0.0644, 20.9714]])

In [58]:
# Element wise operation 
# Division
t1/t2

tensor([[0.0200, 0.0200],
        [0.0200, 0.0200]])

In [65]:
ten1 = torch.tensor([[3,3],[3,3]], dtype=torch.int32) # 2x2 
ten2 = torch.tensor([[16,15],[16,15]], dtype=torch.int32) # 2x2 

In [66]:
# Element wise operation 
# Mod
ten2%3

tensor([[1, 0],
        [1, 0]], dtype=torch.int32)

In [67]:
ten2/ten1

tensor([[5.3333, 5.0000],
        [5.3333, 5.0000]])

In [68]:
ten3 = torch.tensor([1,-2,3,-4,5])

In [69]:
#abs
torch.abs(ten3)

tensor([1, 2, 3, 4, 5])

In [ ]:
#negative or change of sign
torch.neg(ten3)

tensor([-1,  2, -3,  4, -5])

In [77]:
ten4 = torch.tensor([1.21,-2,32,4.567,3.221,6.5])
ten4

tensor([ 1.2100, -2.0000, 32.0000,  4.5670,  3.2210,  6.5000])

In [79]:
# round
torch.round(ten4)

tensor([ 1., -2., 32.,  5.,  3.,  6.])

In [80]:
# ceil
torch.ceil(ten4)

tensor([ 2., -2., 32.,  5.,  4.,  7.])

In [81]:
# floor
torch.floor(ten4)

tensor([ 1., -2., 32.,  4.,  3.,  6.])

In [78]:
# clamp
torch.clamp(ten4, min=5,max=10)

tensor([ 5.0000,  5.0000, 10.0000,  5.0000,  5.0000,  6.5000])

In [82]:
ten5 = torch.randint(size=(2,3), low=0, high=5, dtype=torch.float32)
ten5

tensor([[4., 4., 2.],
        [0., 4., 3.]])

In [83]:
# sum 
torch.sum(ten5)

tensor(17.)

In [85]:
# column sum
torch.sum(ten5, dim=0)

tensor([4., 8., 5.])

In [86]:
# row sum
torch.sum(ten5, dim=1)

tensor([10.,  7.])

In [87]:
# mean - It need float variable only
torch.mean(ten5)

tensor(2.8333)

In [ ]:
# mean - column wise
torch.mean(ten5, dim=0)

tensor([2.0000, 4.0000, 2.5000])

In [89]:
# mean - row wise
torch.mean(ten5, dim=1)

tensor([3.3333, 2.3333])

In [90]:
# median
torch.median(ten5)

tensor(3.)

In [91]:
# max
torch.max(ten5)

tensor(4.)

In [92]:
# min
torch.min(ten5)

tensor(0.)

In [93]:
# standard deviation
torch.std(ten5)

tensor(1.6021)

In [94]:
# variance 
torch.var(ten5)

tensor(2.5667)

In [ ]:
# argmax  - return indices of max value
torch.argmax(ten5)

tensor(0)

In [ ]:
# argmin
torch.argmin(ten5)

tensor(3)

In [97]:
# Matrix operation
mat1 = torch.randint(size=(3,3), low=1, high=20, dtype=torch.float32)
mat2 = torch.randint(size=(3,3), low=1, high=20, dtype=torch.float32)

In [98]:
mat1

tensor([[ 6., 11., 12.],
        [ 5., 16.,  5.],
        [12., 14., 12.]])

In [99]:
mat2

tensor([[ 6., 16., 16.],
        [17.,  7.,  7.],
        [ 4.,  2., 12.]])

In [100]:
# matrix multiplication
torch.matmul(mat1,mat2)

tensor([[271., 197., 317.],
        [322., 202., 252.],
        [358., 314., 434.]])

In [101]:
torch.dot(mat1,mat2)

RuntimeError: 1D tensors expected, but got 2D and 2D tensors

In [102]:
# dot product
vec1 = torch.tensor([2,4])
vec2 = torch.tensor([3,7])

In [103]:
vec1

tensor([2, 4])

In [104]:
vec2

tensor([3, 7])

In [105]:
torch.dot(vec1,vec2)

tensor(34)

In [106]:
mat1

tensor([[ 6., 11., 12.],
        [ 5., 16.,  5.],
        [12., 14., 12.]])

In [107]:
torch.transpose(mat1)

TypeError: transpose() received an invalid combination of arguments - got (Tensor), but expected one of:
 * (Tensor input, int dim0, int dim1)
 * (Tensor input, name dim0, name dim1)


In [ ]:
torch.transpose(mat1,0,1) # transpose using column to row

tensor([[ 6.,  5., 12.],
        [11., 16., 14.],
        [12.,  5., 12.]])

In [ ]:
torch.transpose(mat1,1,0) # transpose using row to column

tensor([[ 6.,  5., 12.],
        [11., 16., 14.],
        [12.,  5., 12.]])

In [110]:
mat1

tensor([[ 6., 11., 12.],
        [ 5., 16.,  5.],
        [12., 14., 12.]])

In [111]:
# Determinant
torch.det(mat1)

tensor(-732.)

In [112]:
# Inverse of matrix
torch.inverse(mat1)

tensor([[-1.6667e-01, -4.9180e-02,  1.8716e-01],
        [ 3.9085e-09,  9.8361e-02, -4.0984e-02],
        [ 1.6667e-01, -6.5574e-02, -5.6011e-02]])

In [ ]:
# Comparison operation - Greater than
mat1>mat2

tensor([[False, False, False],
        [False,  True, False],
        [ True,  True, False]])

In [ ]:
# Comparison operation - less than
mat1<mat2

tensor([[False,  True,  True],
        [ True, False,  True],
        [False, False, False]])

In [115]:
# Comparison operation - Equal
mat1==mat2

tensor([[ True, False, False],
        [False, False, False],
        [False, False,  True]])

In [116]:
# Comparison operation - NOT Equal
mat1!=mat2

tensor([[False,  True,  True],
        [ True,  True,  True],
        [ True,  True, False]])

In [117]:
# Comparison operation - greater than or Equal
mat1>=mat2

tensor([[ True, False, False],
        [False,  True, False],
        [ True,  True,  True]])

In [118]:
mat1

tensor([[ 6., 11., 12.],
        [ 5., 16.,  5.],
        [12., 14., 12.]])

In [ ]:
# log
torch.log(mat1)

tensor([[1.7918, 2.3979, 2.4849],
        [1.6094, 2.7726, 1.6094],
        [2.4849, 2.6391, 2.4849]])

In [120]:
# exponent
torch.exp(mat1)

tensor([[4.0343e+02, 5.9874e+04, 1.6275e+05],
        [1.4841e+02, 8.8861e+06, 1.4841e+02],
        [1.6275e+05, 1.2026e+06, 1.6275e+05]])

In [121]:
# square root
torch.sqrt(mat1)

tensor([[2.4495, 3.3166, 3.4641],
        [2.2361, 4.0000, 2.2361],
        [3.4641, 3.7417, 3.4641]])

In [122]:
# sigmoid
torch.sigmoid(mat1)


tensor([[0.9975, 1.0000, 1.0000],
        [0.9933, 1.0000, 0.9933],
        [1.0000, 1.0000, 1.0000]])

In [123]:
torch.softmax(mat1)

TypeError: softmax() received an invalid combination of arguments - got (Tensor), but expected one of:
 * (Tensor input, int dim, torch.dtype dtype = None, *, Tensor out = None)
 * (Tensor input, name dim, *, torch.dtype dtype = None)


In [125]:
# softmax
torch.softmax(mat1,dim=0) # applying softmax column wise

tensor([[2.4704e-03, 5.8998e-03, 4.9977e-01],
        [9.0880e-04, 8.7560e-01, 4.5573e-04],
        [9.9662e-01, 1.1850e-01, 4.9977e-01]])

In [ ]:
# softmax
torch.softmax(mat1,dim=1) # applying softmax row wise

tensor([[1.8088e-03, 2.6845e-01, 7.2974e-01],
        [1.6701e-05, 9.9997e-01, 1.6701e-05],
        [1.0651e-01, 7.8699e-01, 1.0651e-01]])