In [2]:
import torch
x = torch.rand(5, 3)
print(x)

tensor([[0.2792, 0.6458, 0.6289],
        [0.6664, 0.0841, 0.6839],
        [0.2411, 0.2686, 0.7603],
        [0.3346, 0.9299, 0.6294],
        [0.2083, 0.8751, 0.8809]])


In [ ]:
# Zero dimension tensor is scalar
# One dimension tensor is vector or arrays
# Two dimension tensor is matrix e.g is Black and white Image
# Three dimension tensor is tensor e.g is Colored image a.k.a RGB-alpha image where alpha is intensity 

In [3]:
print(torch.__version__)

2.11.0+cpu


In [4]:
if torch.cuda.is_available():
    print("GPU is available!!")
    print(f"GPU is : {torch.cuda.get_device_name(0)}")
else: 
    print("GPU is not available!!")

GPU is not available!!


In [6]:
# empty tensor
t1 = torch.empty(3,3)  # allocated the memory for a tensor
t1

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [7]:
type(t1)

torch.Tensor

In [8]:
t0 = torch.zeros(3,3)
t0

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [9]:
t_ones = torch.ones(3,3)
t_ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [10]:
t_rand = torch.rand(3,3)
t_rand # creating 3,3 tensor with random values

tensor([[0.5134, 0.4430, 0.7193],
        [0.7262, 0.4609, 0.8585],
        [0.0796, 0.0245, 0.4880]])

In [12]:
# use of seed to keep random value same
t_rand_unseed= torch.rand(3,3)
t_rand_unseed
torch.manual_seed(100) # creating seed for next 100 lines this seed will create same random value
t_rand_seed1 = torch.rand(3,3)
t_rand_seed1

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539],
        [0.2627, 0.0428, 0.2080]])

In [13]:
# Custom tensors
my_tensor = torch.tensor([[1,2,3],[4,5,6]])
my_tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
# Tensor creation
print("arrange: ", torch.arange(0,10,2)) # 0 to 10 with steps of 2 
print("Linear space: ", torch.linspace(0,20,10)) # 0 to 20 in 10 division 
print("EYE : ", torch.eye(5)) # 1 in diagonal for 5x5 tensor  
print("Full : ", torch.full((3,3),7)) # 3x3 tensor with 7 in all values  

arrange:  tensor([0, 2, 4, 6, 8])
Linear space:  tensor([ 0.0000,  2.2222,  4.4444,  6.6667,  8.8889, 11.1111, 13.3333, 15.5556,
        17.7778, 20.0000])
EYE :  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
Full :  tensor([[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]])


In [ ]:
# my_tensor
my_tensor.shape # two rows and three column 

torch.Size([2, 3])

In [ ]:
# creating similar shape tensor as my_tensor with random data
my_tensor1 = torch.empty_like(my_tensor)
my_tensor1 

tensor([[4651718018098673892, 4687746815130686806, 4707762810140083996],
        [4723775612160369550,          1101004800,                   0]])

In [19]:
# creating similar shape tensor as my_tensor with all zero
my_tensor0 = torch.zeros_like(my_tensor)
my_tensor0

tensor([[0, 0, 0],
        [0, 0, 0]])

In [20]:
# creating similar shape tensor as my_tensor with all ones
my_tensor11 = torch.ones_like(my_tensor)
my_tensor11

tensor([[1, 1, 1],
        [1, 1, 1]])

In [21]:
# creating similar shape tensor as my_tensor with all random float value
my_tensor2 = torch.rand_like(my_tensor)
my_tensor2

NotImplementedError: "check_uniform_bounds" not implemented for 'Long'

In [22]:
# Datatypes
my_tensor.dtype

torch.int64

In [ ]:
my_f_tensor = torch.rand([3,3]) # created 3x3 random tensor 
my_f_tensor

tensor([[0.1180, 0.1217, 0.7356],
        [0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

In [27]:
my_i_tensor = torch.rand([3,3], dtype=torch.float16) # created 3x3 random tensor  .rand works with float only
my_i_tensor

tensor([[0.5454, 0.0420, 0.1885],
        [0.8257, 0.9277, 0.9395],
        [0.2026, 0.4380, 0.5688]], dtype=torch.float16)

In [28]:
my_i8_tensor = torch.tensor([
    [1.0,2.0],
    [3.0,4.0],
    ], dtype=torch.int8) # created 3x3 random tensor  .rand works with float only
my_i8_tensor

tensor([[1, 2],
        [3, 4]], dtype=torch.int8)