In [2]:
import torch
x = torch.rand(5, 3)
print(x)

tensor([[0.2792, 0.6458, 0.6289],
        [0.6664, 0.0841, 0.6839],
        [0.2411, 0.2686, 0.7603],
        [0.3346, 0.9299, 0.6294],
        [0.2083, 0.8751, 0.8809]])


In [ ]:
# Zero dimension tensor is scalar
# One dimension tensor is vector or arrays
# Two dimension tensor is matrix e.g is Black and white Image
# Three dimension tensor is tensor e.g is Colored image a.k.a RGB-alpha image where alpha is intensity 

In [3]:
print(torch.__version__)

2.11.0+cpu


In [4]:
if torch.cuda.is_available():
    print("GPU is available!!")
    print(f"GPU is : {torch.cuda.get_device_name(0)}")
else: 
    print("GPU is not available!!")

GPU is not available!!


In [6]:
# empty tensor
t1 = torch.empty(3,3)  # allocated the memory for a tensor
t1

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [7]:
type(t1)

torch.Tensor

In [8]:
t0 = torch.zeros(3,3)
t0

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [9]:
t_ones = torch.ones(3,3)
t_ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])