In [2]:
import numpy as np

In [ ]:
a = np.array([10,20,30,40,50,60,70,80,90])
print(a)
print(type(a))
print(a[3]) # its 40
print(a[1:5])
a[1:5]
print(a[:5])
a[3] = 340 # changing the value
print(a)

[10 20 30 40 50 60 70 80 90]
<class 'numpy.ndarray'>
40
[20 30 40 50]
[10 20 30 40 50]
[ 10  20  30 340  50  60  70  80  90]


In [13]:
# multi-dimension array
a_mul = np.array([
    [10,20,30],
    [25,45,55],
    [50,60,70]
]) 
print(a_mul[0])
print(a_mul[0,2]) # 30

[10 20 30]
30


In [14]:
a_mul.shape # attribute of np array

(3, 3)

In [19]:
a_3d = np.array([
    [
    [1,1,1],
    [2,2,2],
    [3,3,3] 
    ],
    [
    [4,4,4],
    [5,5,5],
    [6,6,6]
    ]
    ])

In [20]:
a_3d.shape

(2, 3, 3)

In [21]:
a_3d_1 = np.array([
    [
    [1,1,1],
    [2,2,2],
    [3,3,3] 
    ],
    [
    [4,4,4],
    [5,5,5]
    
    ]
    ])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [22]:
a_3d_2 = np.array([
    [
    [1,1,1],
    [2,2,2],
   
    ],
    [
    [4,4,4],
    [5,5,5],
  
    ]
    ])

In [ ]:
a_3d_2.shape # be careful with shape and symmetry 

(2, 2, 3)

In [ ]:
a_3d_2.ndim # The dimension

3

In [ ]:
a_3d_2[0,1,2] # accessing element in 3d array

np.int64(2)

In [29]:
a_3d_2[1,1,2]

np.int64(5)

In [30]:
a_3d_2[1,1,3]

IndexError: index 3 is out of bounds for axis 2 with size 3

In [31]:
a_3d_2.size

12

In [32]:
a_3d_2.dtype

dtype('int64')

In [33]:
a_3s_str = np.array([
    [
        [1,2,3],
        [2,'hi',5]
    ],
    [
        [7,[2,3],8],
        [7,'bye',9]
    ]
])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 3 dimensions. The detected shape was (2, 2, 3) + inhomogeneous part.

In [34]:
a_3s_str = np.array([
    [
        [1,2,3],
        [2,'hi',5]
    ],
    [
        [7,66,8],
        [7,'bye',9]
    ]
])

In [35]:
a_3s_str.dtype


dtype('<U21')

In [36]:
a_3s_str[0][1][1]

np.str_('hi')

In [37]:
a_3s_str[0][1][1].dtype

dtype('<U2')

In [40]:
a_3s_str = np.array([
    [
        [1,2,3],
        [2,'hi',5]
    ],
    [
        [7,66,8],
        [7,'bye',9]
    ]
], dtype=np.int32)

ValueError: invalid literal for int() with base 10: 'hi'

In [41]:
a_3s_str = np.array([
    [
        [1,2,3],
        [2,'6',5]
    ],
    [
        [7,66,8],
        [7,'3',9]
    ]
], dtype=np.int32)

In [42]:
a_3s_str.dtype

dtype('int32')

In [43]:
d = {'k':'val'}
a_3s_obj = np.array([
    [
        [1,2,3],
        [2,d,5]
    ]
])

In [ ]:
#a_3s_obj.dtype  # this is python regular object
print(a_3s_obj.dtype)

object


In [ ]:
print(type(a_3s_obj[0,0,1]))  # regular python object

<class 'int'>


In [3]:
# Filling tensor with default values
arr = np.full((2,3,4),5)
arr

array([[[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]],

       [[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]]])

In [5]:
arr0 = np.zeros((2,3,4)) # tensor with zeros
arr0

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [6]:
arr1 = np.ones((2,3,4)) # tensor with ones
arr1

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [10]:
arr2 = np.empty((3,3,4)) # tensor space is allocated with garbage value NOT random value
arr2

array([[[6.82022302e-312, 1.19069821e-321, 0.00000000e+000,
         0.00000000e+000],
        [1.06811354e-306, 1.16097020e-028, 1.26138597e-076,
         2.04331192e-028],
        [1.14217233e-071, 1.04917183e-153, 5.23081515e-143,
         7.48823382e-067]],

       [[8.45365151e+169, 5.97978454e+174, 6.50035437e+169,
         6.53453919e-144],
        [3.59751658e+252, 1.46901661e+179, 8.37404147e+242,
         4.31999013e-096],
        [4.82337723e+228, 5.78534146e+174, 6.10523880e+169,
         5.44910125e-090]],

       [[2.32201935e-056, 1.20129528e-075, 5.04621343e+180,
         1.94918963e-153],
        [4.99722968e+174, 2.32783824e-057, 8.16498693e-043,
         2.02373684e-052],
        [1.04917877e-153, 9.08366791e+223, 5.82381891e-144,
         3.91793118e-317]]])

In [12]:
vec = np.arange(0,10,2) # generating a vector with a range from 0 to 10 and step size of 2
vec

array([0, 2, 4, 6, 8])

In [13]:
lin_space = np.linspace(0, 1000, 4) # dividing a range into linear space
lin_space

array([   0.        ,  333.33333333,  666.66666667, 1000.        ])

In [16]:
print(np.nan) # nan value
print(np.inf) # infinity or inf
print(np.isnan(np.nan)) # checking nan
print(np.isinf(np.inf)) # checking inf

nan
inf
True
True


In [19]:
print(np.sqrt(-1)) # return nan
print(np.array([20])/0) # division by zero gives inf as output

nan
[inf]


C:\Users\Mohnish\AppData\Local\Temp\ipykernel_16696\3144365119.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1)) # return nan
C:\Users\Mohnish\AppData\Local\Temp\ipykernel_16696\3144365119.py:2: RuntimeWarning: divide by zero encountered in divide
  print(np.array([20])/0) # division by zero gives inf as output


In [20]:
l1 = [1,2,3,4,5]
l2 = [6,7,8,9,10]

a1 = np.array(l1)
a2 = np.array(l2)

print(l1*2)
print(a1*2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]
