In [2]:
import numpy as np

In [ ]:
a = np.array([10,20,30,40,50,60,70,80,90])
print(a)
print(type(a))
print(a[3]) # its 40
print(a[1:5])
a[1:5]
print(a[:5])
a[3] = 340 # changing the value
print(a)

[10 20 30 40 50 60 70 80 90]
<class 'numpy.ndarray'>
40
[20 30 40 50]
[10 20 30 40 50]
[ 10  20  30 340  50  60  70  80  90]


In [13]:
# multi-dimension array
a_mul = np.array([
    [10,20,30],
    [25,45,55],
    [50,60,70]
]) 
print(a_mul[0])
print(a_mul[0,2]) # 30

[10 20 30]
30


In [14]:
a_mul.shape # attribute of np array

(3, 3)

In [19]:
a_3d = np.array([
    [
    [1,1,1],
    [2,2,2],
    [3,3,3] 
    ],
    [
    [4,4,4],
    [5,5,5],
    [6,6,6]
    ]
    ])

In [20]:
a_3d.shape

(2, 3, 3)

In [21]:
a_3d_1 = np.array([
    [
    [1,1,1],
    [2,2,2],
    [3,3,3] 
    ],
    [
    [4,4,4],
    [5,5,5]
    
    ]
    ])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [22]:
a_3d_2 = np.array([
    [
    [1,1,1],
    [2,2,2],
   
    ],
    [
    [4,4,4],
    [5,5,5],
  
    ]
    ])

In [ ]:
a_3d_2.shape # be careful with shape and symmetry 

(2, 2, 3)

In [ ]:
a_3d_2.ndim # The dimension

3

In [ ]:
a_3d_2[0,1,2] # accessing element in 3d array

np.int64(2)

In [29]:
a_3d_2[1,1,2]

np.int64(5)

In [30]:
a_3d_2[1,1,3]

IndexError: index 3 is out of bounds for axis 2 with size 3

In [31]:
a_3d_2.size

12

In [32]:
a_3d_2.dtype

dtype('int64')

In [33]:
a_3s_str = np.array([
    [
        [1,2,3],
        [2,'hi',5]
    ],
    [
        [7,[2,3],8],
        [7,'bye',9]
    ]
])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 3 dimensions. The detected shape was (2, 2, 3) + inhomogeneous part.

In [34]:
a_3s_str = np.array([
    [
        [1,2,3],
        [2,'hi',5]
    ],
    [
        [7,66,8],
        [7,'bye',9]
    ]
])

In [35]:
a_3s_str.dtype


dtype('<U21')

In [36]:
a_3s_str[0][1][1]

np.str_('hi')

In [37]:
a_3s_str[0][1][1].dtype

dtype('<U2')

In [40]:
a_3s_str = np.array([
    [
        [1,2,3],
        [2,'hi',5]
    ],
    [
        [7,66,8],
        [7,'bye',9]
    ]
], dtype=np.int32)

ValueError: invalid literal for int() with base 10: 'hi'

In [41]:
a_3s_str = np.array([
    [
        [1,2,3],
        [2,'6',5]
    ],
    [
        [7,66,8],
        [7,'3',9]
    ]
], dtype=np.int32)

In [42]:
a_3s_str.dtype

dtype('int32')

In [43]:
d = {'k':'val'}
a_3s_obj = np.array([
    [
        [1,2,3],
        [2,d,5]
    ]
])

In [ ]:
#a_3s_obj.dtype  # this is python regular object
print(a_3s_obj.dtype)

object


In [ ]:
print(type(a_3s_obj[0,0,1]))  # regular python object

<class 'int'>


In [3]:
# Filling tensor with default values
arr = np.full((2,3,4),5)
arr

array([[[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]],

       [[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]]])