In [1]:
import numpy as np

In [ ]:
a = np.array([10,20,30,40,50,60,70,80,90])
print(a)
print(type(a))
print(a[3]) # its 40
print(a[1:5])
a[1:5]
print(a[:5])
a[3] = 340 # changing the value
print(a)

[10 20 30 40 50 60 70 80 90]
<class 'numpy.ndarray'>
40
[20 30 40 50]
[10 20 30 40 50]
[ 10  20  30 340  50  60  70  80  90]


In [11]:
# multi-dimension array
a_mul = np.array([
    [10,20,30],
    [25,45,55],
    [50,60,70]
]) 
print(a_mul[0])
print(a_mul[0,2]) # 30

[10 20 30]
30


In [ ]:
a_mul.shape # attribute of np array

(3, 3)